[2025-08-19T13:12:56.325+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: customer_metrics.load_customer_transaction_raw scheduled__2025-08-18T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
