[2025-06-23T14:52:07.230+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-23T14:52:07.262+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_self_dag.task2 manual__2025-06-23T14:52:00.690323+00:00 [queued]>
[2025-06-23T14:52:07.280+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_self_dag.task2 manual__2025-06-23T14:52:00.690323+00:00 [queued]>
[2025-06-23T14:52:07.281+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-23T14:52:07.303+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): task2> on 2025-06-23 14:52:00.690323+00:00
[2025-06-23T14:52:07.318+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_self_dag', 'task2', 'manual__2025-06-23T14:52:00.690323+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmptxo1ads5']
[2025-06-23T14:52:07.317+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=533) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-23T14:52:07.320+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask task2
[2025-06-23T14:52:07.320+0000] {standard_task_runner.py:72} INFO - Started process 536 to run task
[2025-06-23T14:52:07.391+0000] {task_command.py:467} INFO - Running <TaskInstance: my_self_dag.task2 manual__2025-06-23T14:52:00.690323+00:00 [running]> on host ef8c6abb536a
[2025-06-23T14:52:07.516+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Om' AIRFLOW_CTX_DAG_ID='my_self_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T14:52:00.690323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T14:52:00.690323+00:00'
[2025-06-23T14:52:07.518+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-23T14:52:07.546+0000] {logging_mixin.py:190} INFO - I am fine.
[2025-06-23T14:52:07.547+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-06-23T14:52:07.564+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-23T14:52:07.565+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_self_dag, task_id=task2, run_id=manual__2025-06-23T14:52:00.690323+00:00, execution_date=20250623T145200, start_date=20250623T145207, end_date=20250623T145207
[2025-06-23T14:52:07.619+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-23T14:52:07.641+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-23T14:52:07.645+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
